'use client'

import { useState, useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { toast } from 'sonner'

interface Company {
  id: number
  code: string
  name: { ko: string; en: string; ja: string; zh: string }
}

interface Department {
  id: number
  company_id: number
  parent_id: number | null
  code: string
  name: { ko: string; en: string; ja: string; zh: string }
  description?: { ko: string; en: string; ja: string; zh: string }
  level: number
  path: string
  company_name: { ko: string; en: string; ja: string; zh: string }
  company_code: string
  parent_name?: { ko: string; en: string; ja: string; zh: string }
  user_count: number
  is_active: boolean
  created_at: string
}

interface DepartmentFormData {
  company_id: string
  parent_id: string
  code: string
  name: { ko: string; en: string; ja: string; zh: string }
  description: { ko: string; en: string; ja: string; zh: string }
}

interface DepartmentFormModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  department?: Department | null
  companyId?: number | null
  parentId?: number | null
  onSuccess?: () => void
}

export function DepartmentFormModal({
  open,
  onOpenChange,
  department,
  companyId,
  parentId,
  onSuccess,
}: DepartmentFormModalProps) {
  const { t, i18n } = useTranslation('departmentManagement')
  const currentLang = i18n.language as 'ko' | 'en' | 'ja' | 'zh'

  const [companies, setCompanies] = useState<Company[]>([])
  const [availableParents, setAvailableParents] = useState<Department[]>([])
  const [loading, setLoading] = useState(false)

  const [formData, setFormData] = useState<DepartmentFormData>({
    company_id: companyId?.toString() || '',
    parent_id: parentId?.toString() || '',
    code: '',
    name: { ko: '', en: '', ja: '', zh: '' },
    description: { ko: '', en: '', ja: '', zh: '' }
  })

  // Reset form when modal opens or props change
  useEffect(() => {
    if (open) {
      if (department) {
        // Edit mode
        setFormData({
          company_id: department.company_id.toString(),
          parent_id: department.parent_id?.toString() || '',
          code: department.code,
          name: department.name,
          description: department.description || { ko: '', en: '', ja: '', zh: '' }
        })
        fetchAvailableParents(department.company_id.toString(), department.id)
      } else {
        // Create mode
        setFormData({
          company_id: companyId?.toString() || '',
          parent_id: parentId?.toString() || '',
          code: '',
          name: { ko: '', en: '', ja: '', zh: '' },
          description: { ko: '', en: '', ja: '', zh: '' }
        })
        if (companyId) {
          fetchAvailableParents(companyId.toString())
        }
      }
    }
  }, [open, department, companyId, parentId])

  // Fetch companies on mount
  useEffect(() => {
    fetchCompanies()
  }, [])

  const fetchCompanies = async () => {
    try {
      const res = await fetch('/api/admin/companies')
      const data = await res.json()
      if (data.success) {
        setCompanies(data.companies)
      }
    } catch (error) {
      console.error('Failed to fetch companies:', error)
    }
  }

  const fetchAvailableParents = async (companyId: string, excludeId?: number) => {
    try {
      const res = await fetch(`/api/admin/departments?companyId=${companyId}`)
      const data = await res.json()
      if (data.success) {
        let parents = data.departments
        if (excludeId) {
          // Exclude current department and its children
          parents = parents.filter((d: Department) =>
            d.id !== excludeId && !d.path.includes(`/${excludeId}/`)
          )
        }
        setAvailableParents(parents)
      }
    } catch (error) {
      console.error('Failed to fetch parent departments:', error)
    }
  }

  const handleCompanyChange = (companyId: string) => {
    setFormData({ ...formData, company_id: companyId, parent_id: '' })
    if (companyId) {
      fetchAvailableParents(companyId, department?.id)
    } else {
      setAvailableParents([])
    }
  }

  const handleSubmit = async () => {
    // Validation (code is auto-generated by DB)
    if (!formData.company_id || !formData.name.ko || !formData.name.en || !formData.name.ja || !formData.name.zh) {
      toast.error(t('nameRequired'))
      return
    }

    try {
      setLoading(true)
      const url = department
        ? `/api/admin/departments/${department.id}`
        : '/api/admin/departments'

      const method = department ? 'PUT' : 'POST'

      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          company_id: parseInt(formData.company_id),
          parent_id: formData.parent_id && formData.parent_id !== 'none' ? parseInt(formData.parent_id) : null,
          name: formData.name,
          description: formData.description
        })
      })

      const data = await res.json()

      if (data.success) {
        toast.success(department ? t('departmentUpdated') : t('departmentCreated'))
        onOpenChange(false)
        if (onSuccess) {
          onSuccess()
        }
      } else {
        toast.error(data.error || t('error'))
      }
    } catch (error) {
      console.error('Failed to save department:', error)
      toast.error(t('error'))
    } finally {
      setLoading(false)
    }
  }

  const getIndentedName = (dept: Department) => {
    const indent = '　'.repeat(dept.level)
    return `${indent}${dept.name[currentLang]}`
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {department ? t('editDepartment') : t('createDepartment')}
          </DialogTitle>
          <DialogDescription>{t('description')}</DialogDescription>
        </DialogHeader>

        <Tabs defaultValue="basic" className="w-full">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="basic">{t('basicInfo')}</TabsTrigger>
            <TabsTrigger value="multilingual">{t('multilingual')}</TabsTrigger>
          </TabsList>

          <TabsContent value="basic" className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="company">{t('company')} *</Label>
              <Select
                value={formData.company_id}
                onValueChange={handleCompanyChange}
                disabled={!!department || !!companyId}
              >
                <SelectTrigger>
                  <SelectValue placeholder={t('selectCompany')} />
                </SelectTrigger>
                <SelectContent>
                  {companies.map((company) => (
                    <SelectItem key={company.id} value={company.id.toString()}>
                      {company.name[currentLang]} ({company.code})
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="parent">{t('parentDepartment')}</Label>
              <Select
                value={formData.parent_id}
                onValueChange={(value) => setFormData({ ...formData, parent_id: value })}
                disabled={!formData.company_id || !!parentId}
              >
                <SelectTrigger>
                  <SelectValue placeholder={t('selectParent')} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">{t('noParent')}</SelectItem>
                  {availableParents.map((dept) => (
                    <SelectItem key={dept.id} value={dept.id.toString()}>
                      {getIndentedName(dept)} ({dept.code})
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="code">{t('code')}</Label>
              <Input
                id="code"
                value={formData.code || t('autoGenerated')}
                disabled={true}
                placeholder={t('autoGeneratedPlaceholder')}
                className="bg-muted text-muted-foreground"
              />
              <p className="text-xs text-muted-foreground">
                {t('codeAutoGeneratedHelp')}
              </p>
            </div>
          </TabsContent>

          <TabsContent value="multilingual" className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="name-ko">{t('nameKo')} *</Label>
              <Input
                id="name-ko"
                value={formData.name.ko}
                onChange={(e) => setFormData({
                  ...formData,
                  name: { ...formData.name, ko: e.target.value }
                })}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="name-en">{t('nameEn')} *</Label>
              <Input
                id="name-en"
                value={formData.name.en}
                onChange={(e) => setFormData({
                  ...formData,
                  name: { ...formData.name, en: e.target.value }
                })}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="name-ja">{t('nameJa')} *</Label>
              <Input
                id="name-ja"
                value={formData.name.ja}
                onChange={(e) => setFormData({
                  ...formData,
                  name: { ...formData.name, ja: e.target.value }
                })}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="name-zh">{t('nameZh')} *</Label>
              <Input
                id="name-zh"
                value={formData.name.zh}
                onChange={(e) => setFormData({
                  ...formData,
                  name: { ...formData.name, zh: e.target.value }
                })}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="desc-ko">{t('descriptionKo')}</Label>
              <Textarea
                id="desc-ko"
                value={formData.description.ko}
                onChange={(e) => setFormData({
                  ...formData,
                  description: { ...formData.description, ko: e.target.value }
                })}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="desc-en">{t('descriptionEn')}</Label>
              <Textarea
                id="desc-en"
                value={formData.description.en}
                onChange={(e) => setFormData({
                  ...formData,
                  description: { ...formData.description, en: e.target.value }
                })}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="desc-ja">{t('descriptionJa')}</Label>
              <Textarea
                id="desc-ja"
                value={formData.description.ja}
                onChange={(e) => setFormData({
                  ...formData,
                  description: { ...formData.description, ja: e.target.value }
                })}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="desc-zh">{t('descriptionZh')}</Label>
              <Textarea
                id="desc-zh"
                value={formData.description.zh}
                onChange={(e) => setFormData({
                  ...formData,
                  description: { ...formData.description, zh: e.target.value }
                })}
              />
            </div>
          </TabsContent>
        </Tabs>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={loading}>
            {t('cancel')}
          </Button>
          <Button onClick={handleSubmit} disabled={loading}>
            {loading ? t('loading') : t('save')}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
